#!/bin/sh
#
# An test hook script to integrate with git to test fsmonitor.
#
# The hook is passed a version (currently 1) and a time in nanoseconds
# formatted as a string and outputs to stdout all files that have been
# modified since the given time. Paths must be relative to the root of
# the working tree and separated by a single NUL.
#
#echo "$0 $*" >&2

if [ "$#" -ne 2 ] ; then
	echo >&2 "$0: exactly 2 arguments expected"
	exit 2
fi

if [ "$1" != 1 ]
then
	echo >&2 "Unsupported core.fsmonitor hook version."
	exit 1
fi

echo "*"
